//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L2_Assessments
    {
        public L2_Assessments()
        {
            this.L2_Assessments_Results = new HashSet<L2_Assessments_Results>();
        }
    
        public System.Guid TaskId { get; set; }
        public Nullable<System.Guid> Asset_Id { get; set; }
    
        public virtual ProjectTask ProjectTask { get; set; }
        public virtual ICollection<L2_Assessments_Results> L2_Assessments_Results { get; set; }
    }
}
